frase = input('Digite algo: ')

print(f'Tipo: {type(frase)}')
print(f'É um alphanumerico? \n{frase.isalnum()}')
print(f'Está em maiusculo? \n{frase.isupper()}')
print(f'É um alpha? \n{frase.isalpha()}')
print(f'Pertence a tabela ascci? \n{frase.isascii()}')
print(f'Está em minusculo:? \n{frase.islower()}')
print(f'É possível imprimir? \n{frase.isprintable()}')
print(f'Esta capitalizado? \n{frase.istitle()}')
print(f'So tem espaços? \n{frase.isspace()}')
